export default {
  SENSE_NOTATION_TAB_NORMAL: '通常（试音/排位）',
  SENSE_NOTATION_TAB_HIGHSCORE: '高分',
  SENSE_NOTATION_TAB_KEIKO: '稽古',

  ALBUM_LEVEL_LABEL: '相册等级：',
  PARTY_LABEL: '编队',
  IMPORT_DATA_LABEL: '导入数据',
  EXPORT_DATA_LABEL: '导出数据',
  EXPORTER_LABEL: '引继码导出工具',
  HIGHSCORE_BUFF_LABEL: '舞台装置：',
  KEIKO_MEMBER_COUNT_LABEL: '编队人数：',
  KEIKO_CALCULATING: '正在计算{0}个组合的最高分',

  THEATER_LEVEL_LABEL: '剧场等级：',
  SIRIUS: 'Sirius',
  EDEN: 'Eden',
  GINGAZA: '银河座',
  DENKI: '剧团电姬',

  ADD: '添加',
  DELETE: '删除',
  NOT_SELECTED: '未选择',
  UPDATE_SELECTION: '更新选中',
  DELETE_SELECTION: '删除选中',
  DELETE_SELECTION_CONFIRM: '确定删除选中的项目吗？',
  SELECTION_COUNT_LABEL: '选中的 {0} 个：',
  UNSELECT_ALL: '取消所有选中',
  SELECTION_EMPTY: '清空',
  ADD_ALL: '添加全部',
  SELECT_ALL: '全选',
  BACK: '返回',

  TAB_CHARA: '角色',
  TAB_POSTER: '海报',
  TAB_ACCESSORY: '饰品',

  CARD_LABEL_STORY: '卡面故事：',
  CARD_LABEL_SENSE: 'Sense: ',
  CARD_LABEL_BLOOM: '突破：',
  CARD_SELECTION_EPISODE_READ_0: '未读',
  CARD_SELECTION_EPISODE_READ_1: '已读前篇',
  CARD_SELECTION_EPISODE_READ_2: '已读后篇',
  POSTER_LABEL_RELEASE: '解放：',

  VOCAL: '歌唱力',
  EXPRESSION: '表现力',
  CONCENTRATION: '集中力',
  PERFORMANCE: '演技力',
  CALC_TABLE_INITIAL: '初始值',
  CALC_TABLE_ALBUM: '相册',
  CALC_TABLE_ACTOR: '演员',
  CALC_TABLE_POSTER: '海报',
  CALC_TABLE_ACCESSORY: '饰品',
  CALC_TABLE_OTHER: '其他',
  CALC_TABLE_TOTAL_BONUS: '总加成',
  CALC_TABLE_FINAL_STAT: '最终值',
  CALC_TOTAL_STAT: '总演技力：',
  CALC_BASE_SCORE: '基础分: ',
  CALC_SENSE_SCORE: 'Sense分: ',
  CALC_STARACT_SCORE: 'StarAct分: ',
  CALC_RESULT_STARACT: '{times}次 / {score}',
  CALC_TOTAL_SCORE: '总分：',
  CALC_STAR_ACT_REQUIREMENTS: 'StarAct需求：',

  LIVE_PHASE_START: '开场前',
  LIVE_PHASE_START_WITH_STARACT: '开场前 | StarAct发动',
  LIVE_PHASE_SENSE: 'Sense发动：{time}',
  LIVE_PHASE_SENSE_FAILED: 'Sense发动失败：{time}',
  LIVE_PHASE_SENSE_WITH_STARACT: 'Sense发动：{time} | StarAct发动',
  LIVE_LOG_LIFE: '生命值变化：{0} + {1} = {2}/1000',
  LIVE_LOG_PGUAGE: 'P槽变化：{0} + {1} = {2}/{3}',
  LIVE_LOG_PGUAGE_LIMIT: 'P槽上限变化：{0} + {1} = {2}/{3}',
  LIVE_LOG_SENSE_FAILED: 'Sense发动失败',
  LIVE_LOG_SENSE_SKIP: '跳过发动',
  LIVE_LOG_SENSE_SCORE: 'Sense加分：{0}',
  LIVE_LOG_STARACT_SCORE: 'StarAct发动，加分：{0}',
  LIVE_LOG_POSTER_SCORE: '海报加分({3})：{0} × {1} = {2}',
  LIVE_LOG_SENSE_UP: 'Sense加成：{0}%，持续{1}秒',
  LIVE_LOG_STARACT_UP: 'StarAct加成：{0}%，持续{1}秒',
  LIVE_LOG_SENSE_SCORE_EXTRA: 'Sense额外加分({3})：{0} × {1} = {2}',
  LIVE_LOG_STARACT_SCORE_EXTRA: 'StarAct额外加分({3})：{0} × {1} = {2}',

  PARTY_DEFAULT_NAME: '队伍',
  PARTY_DELETE_CONFIRM: '确定删除队伍吗？',
  PARTY_DELETE_LAST: '最后一个队伍不能删除',

  FILTER_SELECTION_ALL: '全选',
  FILTER_APPLY: '排序并应用筛选条件',
  FILTER_CHARACTER_RARITY: '稀有度',
  FILTER_CHARACTER_SENSE: 'Sense类型',
  FILTER_CHARACTER_ATTRIBUTE: '属性',
  FILTER_CHARACTER: '角色',
  FILTER_CHARACTER_OBTAIN_METHOD: '获得方式',
  FILTER_CHARACTER_OBTAIN_DEFAULT: '默认',
  FILTER_CHARACTER_OBTAIN_GACHA: '抽卡',
  FILTER_CHARACTER_OBTAIN_LIMITED: '限定',
  FILTER_CHARACTER_OBTAIN_FES: 'Fes限定',
  FILTER_CHARACTER_MAX_TALENT: '最高开花',
  FILTER_CHARACTER_SENSE_EFFECT: 'Sense效果',
  FILTER_POSTER_EFFECT: '海报效果',
  FILTER_ACCESSORY_EFFECT: '饰品效果',

  FILTER_EFFECT_SENSE_SCORE_UP: 'Sense分数提升',
  FILTER_EFFECT_STARACT_SCORE_UP: 'StarAct分数提升',
  FILTER_EFFECT_PGAUGE_UP: 'P条获得量提升',
  FILTER_EFFECT_PGAUGE_GAIN: 'p条增加',
  FILTER_EFFECT_PGAUGE_LIMIT_GAIN: 'p条上限增加',
  FILTER_EFFECT_SCORE_GAIN: '加分',
  FILTER_EFFECT_LIFE_HEALING: '生命回复',
  FILTER_EFFECT_LIFE_GUARD: '生命护盾',
  FILTER_EFFECT_CT_RECAST_DOWN: '当前CT减少',
  FILTER_EFFECT_NONE: '无特殊效果',
  FILTER_EFFECT_VOCAL_UP: '歌唱力提升',
  FILTER_EFFECT_EXPRESSION_UP: '表现力提升',
  FILTER_EFFECT_CONCENTRATION_UP: '集中力提升',
  FILTER_EFFECT_PERFORMANCE_UP: '演技力提升',
  FILTER_EFFECT_SENSE_LIGHT_SELF: '加发动光',
  FILTER_EFFECT_SENSE_LIGHT_SUPPORT: '加<span class="sense-star" data-sense-type="support"></span>光',
  FILTER_EFFECT_SENSE_LIGHT_CONTROL: '加<span class="sense-star" data-sense-type="control"></span>光',
  FILTER_EFFECT_SENSE_LIGHT_AMPLIFICATION: '加<span class="sense-star" data-sense-type="amplification"></span>光',
  FILTER_EFFECT_SENSE_LIGHT_SPECIAL: '加<span class="sense-star" data-sense-type="special"></span>光',
  FILTER_EFFECT_SENSE_LIGHT_VARIABLE: '加<span class="sense-star" data-sense-type="variable"></span>光',
  FILTER_EFFECT_RECAST_DOWN: 'CT减少',
  FILTER_EFFECT_BASE_SCORE_UP: '基础分数提升',
  FILTER_EFFECT_OTHER: '其他',

  LABEL_SORT_AND_FILTER: '筛选排序',
  LABEL_SORT_BY: '排序：',
  LABEL_SORT_DIRECTION: '顺序：',
  LABEL_SORT_ASC: '升序',
  LABEL_SORT_DESC: '降序',
  SORT_KEY_NONE: '不排序',
  SORT_KEY_CHARACTER: '角色',
  SORT_KEY_LEVEL: '等级',
  SORT_KEY_RARITY: '稀有度',
  SORT_KEY_SENSELEVEL: 'Sense等级',
  SORT_KEY_BLOOM: '开花等级',
  SORT_KEY_CT: '发动时间',
  SORT_KEY_RELEASE_DATE: '更新日期',
  SORT_KEY_RELEASE: '上限解放',

  MENU_ANCHOR_TIMELINE: '时间轴',
  MENU_ANCHOR_ALBUM: '相册',
  MENU_ANCHOR_INVENTORY: '仓库',

  LOG_WARNING_EFFECT_NOT_IMPLEMENTED: '未支持的效果：{type} ({id})',
  LOG_WARNING_EFFECT_TRIGGER_NOT_IMPLEMENTED: '未支持的效果触发：{trigger} @ {range} ({id})',
  LOG_WARNING_EFFECT_BRANCH_NOT_IMPLEMENTED: '未支持的分支条件：{condition} ({id})',
  LOG_WARNING_INACCURATE_SCORE_GAIN_ON_SCORE: '按当前得分加分的效果无法精确计算分数',
  LOG_WARNING_EFFECT_SCORE_GAIN_TYPE_NOT_IMPLEMENTED: '未支持的加分类型：{type} ({id})',
  UNDEFINED_STRING: '缺失的文本：{0}',
}
