export default {
  SENSE_NOTATION_TAB_NORMAL: 'オーディション/リーグ',
  SENSE_NOTATION_TAB_HIGHSCORE: 'ハイスコア挑戦',
  SENSE_NOTATION_TAB_KEIKO: '稽古',

  ALBUM_LEVEL_LABEL: 'アルバムレベル：',
  PARTY_LABEL: '編成',
  IMPORT_DATA_LABEL: 'データを導入',
  EXPORT_DATA_LABEL: 'データを保存',
  EXPORTER_LABEL: '連携パスワードで導入するツール',
  HIGHSCORE_BUFF_LABEL: '舞台装置：',
  KEIKO_MEMBER_COUNT_LABEL: '編成人数：',
  KEIKO_CALCULATING: '{0}個の編成の最高スコアを計算中',

  THEATER_LEVEL_LABEL: '劇場レベル：',
  SIRIUS: 'シリウス',
  EDEN: 'Eden',
  GINGAZA: '銀河座',
  DENKI: '劇団電姫',

  ADD: '追加',
  DELETE: '消す',
  NOT_SELECTED: '未選択',
  UPDATE_SELECTION: '選択を更新',
  DELETE_SELECTION: '選択を消す',
  DELETE_SELECTION_CONFIRM: '選択した項目を消しますか？',
  SELECTION_COUNT_LABEL: '選択した {0} 個：',
  UNSELECT_ALL: '全て選択解除',
  SELECTION_EMPTY: 'はずす',

  TAB_CHARA: 'キャラ',
  TAB_POSTER: 'ポスター',
  TAB_ACCESSORY: 'アクセサリー',

  CARD_LABEL_STORY: 'カードストーリー：',
  CARD_LABEL_SENSE: 'センス：',
  CARD_LABEL_BLOOM: '開花：',
  CARD_SELECTION_EPISODE_READ_0: '未読',
  CARD_SELECTION_EPISODE_READ_1: '前編読む',
  CARD_SELECTION_EPISODE_READ_2: '後編読む',
  POSTER_LABEL_RELEASE: '解放：',

  VOCAL: '歌唱力',
  EXPRESSION: '表現力',
  CONCENTRATION: '集中力',
  PERFORMANCE: '演技力',
  CALC_TABLE_INITIAL: '初期',
  CALC_TABLE_ALBUM: 'アルバム',
  CALC_TABLE_ACTOR: 'アクター',
  CALC_TABLE_POSTER: 'ポスター',
  CALC_TABLE_ACCESSORY: 'アクセサリー',
  CALC_TABLE_OTHER: 'その他',
  CALC_TABLE_TOTAL_BONUS: 'ボーナス合計',
  CALC_TABLE_FINAL_STAT: '最終',
  CALC_TOTAL_STAT: '合計演技力：',
  CALC_BASE_SCORE: '基礎スコア：',
  CALC_SENSE_SCORE: 'センススコア: ',
  CALC_STARACT_SCORE: 'スターアクトスコア: ',
  CALC_RESULT_STARACT: '{times}回発動 / {score}',
  CALC_TOTAL_SCORE: 'スコア：',
  CALC_STAR_ACT_REQUIREMENTS: 'スターアクト発動条件：',

  LIVE_PHASE_START: 'ライブ前',
  LIVE_PHASE_START_WITH_STARACT: 'ライブ前 | スターアクト発動',
  LIVE_PHASE_SENSE: 'センス発動：{time}',
  LIVE_PHASE_SENSE_FAILED: 'センス失敗：{time}',
  LIVE_PHASE_SENSE_WITH_STARACT: 'センス発動：{time} | スターアクト発動',
  LIVE_LOG_LIFE: 'ライフ：{0} + {1} = {2}/1000',
  LIVE_LOG_PGUAGE: 'P.ゲージ：{0} + {1} = {2}/{3}',
  LIVE_LOG_PGUAGE_LIMIT: 'P.ゲージ上限：{0} + {1} = {2}/{3}',
  LIVE_LOG_SENSE_FAILED: 'センス失敗',
  LIVE_LOG_SENSE_SKIP: '発動しない',
  LIVE_LOG_SENSE_SCORE: 'センススコア：{0}',
  LIVE_LOG_STARACT_SCORE: 'スターアクト発動、スコア：{0}',
  LIVE_LOG_POSTER_SCORE: 'ポスタースコア({3})：{0} × {1} = {2}',
  LIVE_LOG_SENSE_UP: 'センスブースト：{0}%，{1}秒間持続',
  LIVE_LOG_STARACT_UP: 'スターアクトブースト：{0}%，{1}秒間持続',
  LIVE_LOG_SENSE_SCORE_EXTRA: 'センスボーナススコア({3})：{0} × {1} = {2}',
  LIVE_LOG_STARACT_SCORE_EXTRA: 'スターアクトボーナススコア({3})：{0} × {1} = {2}',

  PARTY_DEFAULT_NAME: 'パーティー',
  PARTY_DELETE_CONFIRM: 'パーティーを消しますか？',
  PARTY_DELETE_LAST: '最後のパーティーは消せません',

  FILTER_SELECTION_ALL: 'すべて',
  FILTER_APPLY: 'ソートしてフィルターを適用',
  FILTER_CHARACTER_RARITY: 'レアリティ',
  FILTER_CHARACTER_SENSE: 'センス',
  FILTER_CHARACTER_ATTRIBUTE: '属性',
  FILTER_CHARACTER: 'キャラクター',
  FILTER_CHARACTER_OBTAIN_METHOD: '入手方法',
  FILTER_CHARACTER_OBTAIN_DEFAULT: '最初から',
  FILTER_CHARACTER_OBTAIN_GACHA: 'ガチャ',
  FILTER_CHARACTER_OBTAIN_LIMITED: '限定',
  FILTER_CHARACTER_OBTAIN_FES: 'フェス限定',
  FILTER_CHARACTER_MAX_TALENT: '最大開花',
  FILTER_CHARACTER_SENSE_EFFECT: 'センス効果',
  FILTER_POSTER_EFFECT: 'ポスター効果',
  FILTER_ACCESSORY_EFFECT: 'アクセサリー効果',

  FILTER_EFFECT_SENSE_SCORE_UP: 'センススコアアップ',
  FILTER_EFFECT_STARACT_SCORE_UP: 'スターアクトスコアアップ',
  FILTER_EFFECT_PGAUGE_UP: 'Pゲージ獲得量アップ',
  FILTER_EFFECT_PGAUGE_GAIN: 'Pゲージ増加',
  FILTER_EFFECT_PGAUGE_LIMIT_GAIN: 'Pゲージ上限増加',
  FILTER_EFFECT_SCORE_GAIN: 'スコアアップ',
  FILTER_EFFECT_LIFE_HEALING: 'ライフ回復',
  FILTER_EFFECT_LIFE_GUARD: 'ライフガード',
  FILTER_EFFECT_CT_RECAST_DOWN: '演出中CT減少',
  FILTER_EFFECT_NONE: '特殊効果なし',
  FILTER_EFFECT_VOCAL_UP: '歌唱力アップ',
  FILTER_EFFECT_EXPRESSION_UP: '表現力アップ',
  FILTER_EFFECT_CONCENTRATION_UP: '集中力アップ',
  FILTER_EFFECT_PERFORMANCE_UP: '演技力アップ',
  FILTER_EFFECT_SENSE_LIGHT_SELF: 'センス光追加',
  FILTER_EFFECT_SENSE_LIGHT_SUPPORT: '<span class="sense-star" data-sense-type="support"></span>追加',
  FILTER_EFFECT_SENSE_LIGHT_CONTROL: '<span class="sense-star" data-sense-type="control"></span>追加',
  FILTER_EFFECT_SENSE_LIGHT_AMPLIFICATION: '<span class="sense-star" data-sense-type="amplification"></span>追加',
  FILTER_EFFECT_SENSE_LIGHT_SPECIAL: '<span class="sense-star" data-sense-type="special"></span>追加',
  FILTER_EFFECT_SENSE_LIGHT_VARIABLE: '<span class="sense-star" data-sense-type="variable"></span>追加',
  FILTER_EFFECT_RECAST_DOWN: 'CT減少',
  FILTER_EFFECT_BASE_SCORE_UP: '基礎スコアアップ',
  FILTER_EFFECT_OTHER: 'その他',

  LABEL_SORT_AND_FILTER: 'フィルター',
  LABEL_SORT_BY: '並び替え：',
  LABEL_SORT_DIRECTION: '順序：',
  LABEL_SORT_ASC: '昇順',
  LABEL_SORT_DESC: '降順',
  SORT_KEY_NONE: 'なし',
  SORT_KEY_CHARACTER: 'キャラクター',
  SORT_KEY_LEVEL: 'レベル',
  SORT_KEY_RARITY: 'レアリティ',
  SORT_KEY_SENSELEVEL: 'センスレベル',
  SORT_KEY_BLOOM: '才能開花',
  SORT_KEY_CT: 'CT',
  SORT_KEY_RELEASE_DATE: 'リリース日',
  SORT_KEY_RELEASE: '上限解放',

  MENU_ANCHOR_TIMELINE: '編成',
  MENU_ANCHOR_ALBUM: 'アルバム',
  MENU_ANCHOR_INVENTORY: 'メンバー',

  LOG_WARNING_EFFECT_NOT_IMPLEMENTED: '効果支援していない：{type} ({id})',
  LOG_WARNING_EFFECT_TRIGGER_NOT_IMPLEMENTED: '効果の条件支援していない：{trigger} @ {range} ({id})',
  LOG_WARNING_EFFECT_BRANCH_NOT_IMPLEMENTED: '分岐条件支援していない：{condition} ({id})',
  LOG_WARNING_INACCURATE_SCORE_GAIN_ON_SCORE: '現在のスコアに基づくボーナスは正確に計算できません',
  LOG_WARNING_EFFECT_SCORE_GAIN_TYPE_NOT_IMPLEMENTED: 'スコアボーナスの種類支援していない：{type} ({id})',
  UNDEFINED_STRING: '不足しているテキスト：{0}',
}
