export default {
  PAGE_TITLE: 'YumeSute Calculator',

  SENSE_NOTATION_TAB_NORMAL: 'Normal (Audition/League）',
  SENSE_NOTATION_TAB_HIGHSCORE: 'Highscore Challenge',
  SENSE_NOTATION_TAB_KEIKO: 'Lesson (Keiko)',
  SENSE_NOTATION_TAB_QUIZ: 'Quiz (Kaimaku Kouen)',

  ALBUM_LEVEL_LABEL: 'Album level: ',
  PARTY_LABEL: 'Party edit',
  IMPORT_DATA_LABEL: 'Load exported',
  EXPORT_DATA_LABEL: 'Export',
  EXPORTER_LABEL: 'Export tool using password (Updated 22/Aug/2025)',
  HIGHSCORE_BUFF_LABEL: 'Stage Boost: ',
  KEIKO_MEMBER_COUNT_LABEL: 'Party size: ',
  KEIKO_CALCULATING: 'Calculating the highest score of {0} party combinations',

  THEATER_LEVEL_LABEL: 'Theater level: ',
  SIRIUS: 'Sirius',
  EDEN: 'Eden',
  GINGAZA: 'Gingaza',
  DENKI: 'Gekidan Denki',
  AQUARS: 'Aquars',

  ADD: 'Add',
  DELETE: 'Delete',
  NOT_SELECTED: 'Not selected',
  UPDATE_SELECTION: 'Update selected',
  DELETE_SELECTION: 'Delete selected',
  DELETE_SELECTION_CONFIRM: 'Delete selected items?',
  SELECTION_COUNT_LABEL: 'Selected {0} items: ',
  UNSELECT_ALL: 'Unselect all',
  SELECTION_EMPTY: 'Empty',
  ADD_ALL: 'Add all',
  SELECT_ALL: 'Select all',
  BACK: 'Back',

  VIEW_GACHA: 'View Gacha',
  GACHA_TYPE_PICKUP: 'Pick Up',
  GACHA_TYPE_SELECT: 'Selectable Pick Up',

  TAB_CHARA: 'Character',
  TAB_POSTER: 'Poster',
  TAB_ACCESSORY: 'Accessory',

  CARD_LABEL_STORY: 'Card story: ',
  CARD_LABEL_SENSE: 'Sense: ',
  CARD_LABEL_BLOOM: 'Bloom: ',
  CARD_LABEL_AWAKEN: 'Awaken',
  CARD_SELECTION_EPISODE_READ_0: 'Not read',
  CARD_SELECTION_EPISODE_READ_1: 'Read Episode 1',
  CARD_SELECTION_EPISODE_READ_2: 'Read Episode 2',
  POSTER_LABEL_RELEASE: 'Release: ',

  VOCAL: 'Vocal',
  EXPRESSION: 'Expression',
  CONCENTRATION: 'Concentration',
  PERFORMANCE: 'Performance',
  CALC_TABLE_INITIAL: 'Initial',
  CALC_TABLE_ALBUM: 'Album',
  CALC_TABLE_ACTOR: 'Actor',
  CALC_TABLE_POSTER: 'Poster',
  CALC_TABLE_ACCESSORY: 'Accessory',
  CALC_TABLE_OTHER: 'Other',
  CALC_TABLE_TOTAL_BONUS: 'Total Bonus',
  CALC_TABLE_EXTRA_UP: 'Extra Bonus',
  CALC_TABLE_FINAL_STAT: 'Final Stat',
  CALC_TOTAL_STAT: 'Total stat: ',
  CALC_BASE_SCORE: 'Base score: ',
  CALC_SENSE_SCORE: 'Sense score: ',
  CALC_STARACT_SCORE: 'Star Act score: ',
  CALC_RESULT_STARACT: '{times} times / {score}',
  CALC_TOTAL_SCORE: 'Total score: ',
  CALC_STAR_ACT_REQUIREMENTS: 'StarAct requirements: ',

  LIVE_PHASE_START: 'Before start',
  LIVE_PHASE_START_WITH_STARACT: 'Before start | StarAct activated',
  LIVE_PHASE_SENSE: 'Sense activated: {time}',
  LIVE_PHASE_SENSE_FAILED: 'Sense failed: {time}',
  LIVE_PHASE_SENSE_WITH_STARACT: 'Sense activated: {time} | StarAct activated',
  LIVE_LOG_LIFE: 'Life changed: {0} + {1} = {2}/1000',
  LIVE_LOG_PGUAGE: 'P gauge changed: {0} + {1} = {2}/{3}',
  LIVE_LOG_PGUAGE_LIMIT: 'P gauge limit changed: {0} + {1} = {2}/{3}',
  LIVE_LOG_SENSE_FAILED: 'Sense failed',
  LIVE_LOG_SENSE_SKIP: 'Skipped',
  LIVE_LOG_SENSE_SCORE: 'Sense score: {0}',
  LIVE_LOG_STARACT_SCORE: 'Star Act activated, score: {0}',
  LIVE_LOG_POSTER_SCORE: 'Poster bonus ({3}): {0} × {1} = {2}',
  LIVE_LOG_SENSE_UP: 'Sense bonus: {0}%, lasts {1} sec',
  LIVE_LOG_STARACT_UP: 'Star Act bonus: {0}%, lasts{1} sec',
  LIVE_LOG_SENSE_SCORE_EXTRA: 'Sense bonus ({3}): {0} × {1} = {2}',
  LIVE_LOG_STARACT_SCORE_EXTRA: 'Star Act bonus ({3}): {0} × {1} = {2}',

  PARTY_DEFAULT_NAME: 'Party',
  PARTY_DELETE_CONFIRM: 'Delete this party?',
  PARTY_DELETE_LAST: 'Last party cannot be deleted',

  FILTER_SELECTION_ALL: 'Select all',
  FILTER_APPLY: 'Sort & Apply filter',
  FILTER_CHARACTER_RARITY: 'Rarity',
  FILTER_CHARACTER_SENSE: 'Sense Type',
  FILTER_CHARACTER_ATTRIBUTE: 'Attribute',
  FILTER_CHARACTER: 'Character',
  FILTER_CHARACTER_OBTAIN_METHOD: 'Obtain Method',
  FILTER_CHARACTER_OBTAIN_DEFAULT: 'Default',
  FILTER_CHARACTER_OBTAIN_GACHA: 'Gacha',
  FILTER_CHARACTER_OBTAIN_EVENT: 'Event',
  FILTER_CHARACTER_OBTAIN_LIMITED: 'Limited',
  FILTER_CHARACTER_OBTAIN_FES: 'Fes Limited',
  FILTER_CHARACTER_MAX_TALENT: 'Max Bloom Stage',
  FILTER_CHARACTER_SENSE_EFFECT: 'Sense Effect',
  FILTER_POSTER_EFFECT: 'Poster Effect',
  FILTER_ACCESSORY_EFFECT: 'Accessory Effect',
  FILTER_EFFECT_CONDITION: 'Effect Condition',

  FILTER_EFFECT_SENSE_SCORE_UP: 'Sense score bonus',
  FILTER_EFFECT_STARACT_SCORE_UP: 'Star Act score bonus',
  FILTER_EFFECT_PGAUGE_UP: 'P. gauge bonus',
  FILTER_EFFECT_PGAUGE_GAIN: 'P. gauge gain',
  FILTER_EFFECT_PGAUGE_LIMIT_GAIN: 'P. gauge limit increase',
  FILTER_EFFECT_SCORE_GAIN: 'Score bonus',
  FILTER_EFFECT_LIFE_HEALING: 'Life healing',
  FILTER_EFFECT_LIFE_GUARD: 'Life guard',
  FILTER_EFFECT_CT_RECAST_DOWN: 'Current CT decrease',
  FILTER_EFFECT_PERFORMANCE_DUPLICATE_UP: 'Performance bonus',
  FILTER_EFFECT_NONE: 'No special effect',
  FILTER_EFFECT_VOCAL_UP: 'Vo. bonus',
  FILTER_EFFECT_EXPRESSION_UP: 'Ex. bonus',
  FILTER_EFFECT_CONCENTRATION_UP: 'Co. bonus',
  FILTER_EFFECT_PERFORMANCE_UP: 'Perf. bonus',
  FILTER_EFFECT_PERFORMANCE_LIMIT_UP: 'Perf. limit increase',
  FILTER_EFFECT_SENSE_LIGHT_SELF: 'Add sense light',
  FILTER_EFFECT_SENSE_LIGHT_SUPPORT: 'Add <span class="sense-star" data-sense-type="support"></span>',
  FILTER_EFFECT_SENSE_LIGHT_CONTROL: 'Add <span class="sense-star" data-sense-type="control"></span>',
  FILTER_EFFECT_SENSE_LIGHT_AMPLIFICATION: 'Add <span class="sense-star" data-sense-type="amplification"></span>',
  FILTER_EFFECT_SENSE_LIGHT_SPECIAL: 'Add <span class="sense-star" data-sense-type="special"></span>',
  FILTER_EFFECT_SENSE_LIGHT_VARIABLE: 'Add <span class="sense-star" data-sense-type="variable"></span>',
  FILTER_EFFECT_RECAST_DOWN: 'CT decrease',
  FILTER_EFFECT_BASE_SCORE_UP: 'Base score bonus',
  FILTER_EFFECT_REWARD_UP: 'Extra rewards',
  FILTER_EFFECT_OTHER: 'Other',

  FILTER_EFFECT_CONDITION_CHARACTER: 'Character',
  FILTER_EFFECT_CONDITION_COMPANY: 'Theater',
  FILTER_EFFECT_CONDITION_ATTRIBUTE: 'Attribute',
  FILTER_EFFECT_CONDITION_NONE: 'No condition',

  LABEL_SORT_AND_FILTER: 'Sort & Filter',
  LABEL_SORT_BY: 'Sort by: ',
  LABEL_SORT_DIRECTION: 'Order: ',
  LABEL_SORT_ASC: 'Ascending',
  LABEL_SORT_DESC: 'Descending',
  SORT_KEY_NONE: 'No sorting',
  SORT_KEY_CHARACTER: 'Character',
  SORT_KEY_LEVEL: 'Level',
  SORT_KEY_RARITY: 'Rarity',
  SORT_KEY_SENSELEVEL: 'Sense Level',
  SORT_KEY_BLOOM: 'Bloom Level',
  SORT_KEY_CT: 'Cooldown Time',
  SORT_KEY_RELEASE_DATE: 'Release Date',
  SORT_KEY_RELEASE: 'Release',
  SORT_KEY_BLOOM_RELEASE_DATE: 'Bloom Cap Release Date',

  MENU_ANCHOR_TIMELINE: 'Timeline',
  MENU_ANCHOR_ALBUM: 'Album',
  MENU_ANCHOR_INVENTORY: 'Inventory',

  LOG_WARNING_EFFECT_NOT_IMPLEMENTED: 'Effect type not implemented: {type} ({id})',
  LOG_WARNING_EFFECT_TRIGGER_NOT_IMPLEMENTED: 'Effect trigger not implemented: {trigger} @ {range} ({id})',
  LOG_WARNING_EFFECT_BRANCH_NOT_IMPLEMENTED: 'Branch condition not implemented: {condition} ({id})',
  LOG_WARNING_INACCURATE_SCORE_GAIN_ON_SCORE: '** Bonus based on current score cannot be accurately calculated',
  LOG_WARNING_EFFECT_SCORE_GAIN_TYPE_NOT_IMPLEMENTED: 'Score gain type not implemented: {type} ({id})',
  UNDEFINED_STRING: 'Missing text template: {0}',
}
